POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haWphQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjI0MjcxMzd9.fYGW-7ZjqgMGKPM30DKrpUPctkkkKni7SrXUPN8jSDY

{
  "title": "Is High Quality Software Worth the Cost?",
  "author": "Martin Fowler",
  "url": "www.martinfowler.com",
  "year": 1999,
  "likes": 10
}